### ISSUE TITLE
De-minify desktop.min.js

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#104]
This file is minified:

https://github.com/m-lab/m-lab.github.io/blob/master/js/desktop.min.js

It's unclear if we have the un-minified source anywhere, but minified JS should not be in source control. We should de-minifiy this using a JS formatter that can apply the formatting rules of the [Google JS style guide](https://google.github.io/styleguide/javascriptguide.xml).

**Comment by shredtechular** [comment]
I'm not able to close issues, so leaving a comment that I think PR #109 addressed this issue and I think it can be closed?
