### ISSUE TITLE
Invalidate CloudFront cache after production builds

### ISSUE THREAD

**Issue by nkinkade** [m-lab/m-lab.github.io#108]
The default (and current) TTL for objects in the CloudFront cache is 1 day, which means that users could be seeing day-old content.  We need to implement a way to invalidate the cache after each production build, but no on other builds, like ones for PRs.

**Comment by nkinkade** [comment]
This is hopefully addressed by PR #107, but we won't know for sure until the PR is merged.

**Comment by nkinkade** [comment]
The command to invalidate the cache is returning this error:

"AWS key missing in the configuration file (RuntimeError)"

It may be that I created the encrypted auth file incorrectly somehow.

**Comment by critzo** [comment]
This is working now I think. Closing.
