### ISSUE TITLE
Inconsistent URLs for "tools" vs. "tests"

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#126]
There is inconsistency with our URLs for tools and tests. The tab is labeled **tests** but the URL for NDT is:

https://www.measurementlab.net/**tools**/ndt/

But then the URL for the index of all tests is:

https://www.measurementlab.net/**tests**/

Suggest changing all URLs to `tests` and adding redirects. At the very least, we should be consistent.

**Comment by georgiamoon** [comment]
+1

**Comment by critzo** [comment]
+1 We've already updated text (on the FAQ page) standardizing on tests

**Comment by critzo** [comment]
How are we redirecting URLs we *used to* provide to their new ones? ie: redirecting /tools/ndt to /tests/ndt  ?

**Comment by mtlynch** [comment]
I believe we can just use a Jekyll plugin add metadata to the page:

https://github.com/jekyll/jekyll-redirect-from

**Comment by mtlynch** [comment]
We also need to add a redirect from `/measurement-lab-tools`. It's our third most popular landing page according to Google Analytics and it currently 404s.

**Comment by critzo** [comment]
@georgiamoon I've attempted to test redirects using the jekyll-redirect-from plugin but it doesn't seem to work for me. It generates the page (for example, when I add `redirect_from: "/measurement-lab-tools/" ` to the front matter of `_pages/tools/03-tests.md` a page is created when the site gets built: `_site/measurement-lab-tools/index.html` but the refresh meta tag isn't populated with a URL. The result is a page trying to constantly refresh to a blank location. 

I've done a workaround in my [branch](https://github.com/critzo/m-lab.github.io), using the method we used to redirect to the viz site, that is adding a redirect_to: variable to the front matter of a new page: `_pages/measurement-lab-tools/index.md`  which you can [preview](https://critzo.github.io/m-lab.github.io/).

I'm wondering if this solution is sufficient or if someone else can get the redirect-from plugin working right we could use it. In this case, to add redirects, we would simply add a stub page like `_pages/measurement-lab-tools/index.md` for any page that needed redirecting, or for 404s we see a lot of, etc.

So for example, if we were to use this method to redirect pages like the test pages currently in `/tools/` we would make the folder `_site/tests/`, copy all the test pages from `_site/tools/*` into it, change their permalinks, and add the `redirect-to: ` URLs to all the old pages in `_site/tools/`

**Comment by georgiamoon** [comment]
Tagging @nkinkade in here too to take a look

**Comment by georgiamoon** [comment]
Tagging @nkinkade in here too to take a look

**Comment by critzo** [comment]
Pinging this thread with an update on redirects. We can do redirects in the way we've done it for the new visualization, redirecting from this page: https://github.com/m-lab/m-lab.github.io/blob/master/_pages/02-visualizations.md  to the viz.measure... site. I believe you can also do the redirect in AWS, though that is less straightforward.

**Comment by critzo** [comment]
I've documented how to do the redirect in AWS here: https://github.com/m-lab/m-lab.github.io/issues/65#issuecomment-314542474

Two ways to do redirects actually. First, is to have a page like https://github.com/m-lab/m-lab.github.io/blob/master/_pages/02-visualizations.md which specifies an external URL to redirect to in the YAML front matter. The second is described in the link at the top of this comment, which is to upload a zero-byte file in the location where your redirect is needed, and then add the redirect metadata item to the object in S3.

**Comment by critzo** [comment]
Resolved with 301 redirects added in AWS.
