### ISSUE TITLE
Simplify markdown on accordion pages

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#127]
On pages with accordion organizers, we should work to make it easier for the author to edit content and not have to manually manage accordion logic. On PR #120 we ran into a lot of issues where the task of writing content was made more difficult by the task of managing accordion logic.

This is currently most problematic on the FAQ page:

https://github.com/m-lab/m-lab.github.io/blob/master/_pages/faq.md

Ideal would be on all of these pages if:

* Content author can author content using only standard markdown and the backend page logic figures out how to organize it into accordion groupings for proper rendering
* Content author does not need to do any kind of metadata management (declaring up front the names or numbers of headings)

**Comment by critzo** [comment]
Since we've decided to do away with the accordion functionality, closing this issue.
