### ISSUE TITLE
Strange bullets in front of Observatory Menu buttons

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/m-lab.github.io#138]
See here:
![screen shot 2016-03-31 at 3 28 01 pm](https://cloud.githubusercontent.com/assets/941210/14188274/4fa05662-f755-11e5-939d-6acc82230ff9.png)

and here:
![screen shot 2016-03-31 at 3 28 19 pm](https://cloud.githubusercontent.com/assets/941210/14188283/54e2ef2c-f755-11e5-803e-6ce9978b18be.png)

I *think* that these are just css issues with what is probably a `<ul>` element.

**Comment by critzo** [comment]
This issue should be resolved by #139. Waiting for cache to refresh to close.
