### ISSUE TITLE
Video play button on front page has drifted to float left

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/m-lab.github.io#161]
Not sure how! But it traveled.

![screen shot 2016-04-08 at 1 33 26 pm](https://cloud.githubusercontent.com/assets/941210/14392254/8153d1b8-fd8e-11e5-86a3-99d2061030c0.png)

**Comment by shredtechular** [comment]
I checked the wayback archive (https://web.archive.org/web/20150912141117/http://www.measurementlab.net/) and it looks like this button has been floated to the left for quite some time and may have been done intentionally (not sure)?

I did play with centering the play button, however, you can see in the screen cap below it does cover part of the the "MLAB" in the video graphic and may not be the optimal placing of the button?  How does centering it vertically/horizontally look to folks?  Is this something that we want or after looking at the placement of the play button, do you think it looks better on the left?  It's okay by me either way, but just wanted to send a screenshot of how it looks centered before implementing this fix?
<img width="1152" alt="screen shot 2016-05-15 at 11 23 25 am" src="https://cloud.githubusercontent.com/assets/2396774/15275079/061a53cc-1a90-11e6-917c-37cc07b31b62.png">

**Comment by georgiamoon** [comment]
Hmm.. It's weird that I never noticed that before.

@critzo @sloane101 thoughts on whether to center the button or leave it where it is?

**Comment by sloane101** [comment]
I'm generally a fan of centered for video play buttons - when it is on the left or the right, I get the impression that it is a slide show, not a video.

**Comment by critzo** [comment]
@georgiamoon @shredtechular @sloane101 I think we should center it. That's generally what I would expect. Not sure when or why it got moved to the left.

**Comment by shredtechular** [comment]
OK, got it!  Thanks for the quick responses, I'll work on centering the play button then!
