### ISSUE TITLE
Chunk footer links by related items

### ISSUE THREAD

**Issue by critzo** [m-lab/m-lab.github.io#168]
About, Contact, Privacy, Terms
FAQ, Blog, RSS 
others ???

**Comment by critzo** [comment]
I've done a quick in-browser mock-up proposing changes to the links in the footer. @georgiamoon do you have feedback or thoughts? Some basic rearranging, removing duplicate reference to the Privacy policy page, removed the "Terms" link since it's a blank page right now anyway.

![image](https://user-images.githubusercontent.com/4633345/28084013-4b860dd2-6645-11e7-94cc-2c84b63f10f7.png)

**Comment by georgiamoon** [comment]
Can we do 3 columns, e.g.:

About
Contact
Discuss List

FAQ
Blog
RSS

Privacy Policy
Acceptable Use Policy

**Comment by critzo** [comment]
Of course! How does this look:
![image](https://user-images.githubusercontent.com/4633345/28117883-1bd24900-66dd-11e7-9a11-a312c85157a1.png)

**Comment by georgiamoon** [comment]
LGTM.
