### ISSUE TITLE
FAQ page has lots of empty space on right

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#176]
The graphic seems to not be resizing properly:
![image](https://cloud.githubusercontent.com/assets/7783288/14440563/6bdec2c6-fffe-11e5-8af8-d4e1fc0ade84.png)

which results in a bunch of empty space on the right:
![image](https://cloud.githubusercontent.com/assets/7783288/14440589/95873838-fffe-11e5-95b8-9050c6324d1b.png)

Tested on Chrome + Nexus 5P

**Comment by shredtechular** [comment]
Confirmed, coding bug, will take a look at this one.
