### ISSUE TITLE
Neubot misalgned on tests page

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#177]
Neubot seems out of alignment on the tests page:

![image](https://cloud.githubusercontent.com/assets/7783288/14440633/cc4a6c3c-fffe-11e5-99de-7dfd083411fc.png)

Tested with Chrome + Nexus 5P

**Comment by shredtechular** [comment]
Checking this locally and against my fork, I believe this is also related to the caching issue described in issue #179.  Will keep an eye on it though once the cache is invalidated at the CDN level.

**Comment by mtlynch** [comment]
I'm still seeing this despite the cache fixes. Let's sit on it for a day and see if it still repros.

**Comment by mtlynch** [comment]
Confirmed, went away. Closing.
