### ISSUE TITLE
Data pages have poor padding on mobile

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#178]
The tables on data pages seem to have strange formatting on mobile where the tables are very close to subsequent text:

![image](https://cloud.githubusercontent.com/assets/7783288/14440734/4b476e40-ffff-11e5-8378-014b9f4a48eb.png)

Compare to desktop version:
![image](https://cloud.githubusercontent.com/assets/7783288/14440746/55f0b108-ffff-11e5-8e17-1a04338de5b9.png)

Tested on Chrome + Nexus 5P

**Comment by shredtechular** [comment]
Confirmed coding issue, will take a look at a fix for this.
