### ISSUE TITLE
CSS broken on GCS page

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#179]
The [GCS page](http://www.measurementlab.net/data/gcs/) seems to be broken on desktop now:

![image](https://cloud.githubusercontent.com/assets/7783288/14440792/987a0bfa-ffff-11e5-90f4-6b9fbde9db0d.png)

**Comment by shredtechular** [comment]
This looks to be a AWS caching issue.  I have built the site locally and pushed the lastest master up to my [fork](http://shredtechular.github.io/m-lab.github.io/data/gcs/) and am not seeing this behavior there.  Should we manually purge or invalidate the site's cache?

Additionally, I wonder if versioning CSS/JS here would prevent these types of caching issues from re-occurring if it is not being purged/invalidated after deploying?

**Comment by mtlynch** [comment]
It looks like you were right and it's a caching issue. Gone now.
