### ISSUE TITLE
NDT test has extraneous scrollbars

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#185]
I'm seeing strange scrollbar behavior with the NDT test. When it first loads, it seems to show an extraneous, inactive scrollbar:

![image](https://cloud.githubusercontent.com/assets/7783288/14790775/d3bf1ef8-0ae0-11e6-9038-6d603d98111a.png)

Clicking the embed button creates another scrollbar that's active, but doesn't seem necessary because all the content fits within the widget:

![image](https://cloud.githubusercontent.com/assets/7783288/14790796/ed30be32-0ae0-11e6-972d-73b62e93cbbb.png)

Observed on Ubuntu 14 + Chrome

**Comment by shredtechular** [comment]
I'm not able to close issues, so leaving a comment that I think PR #186 addressed this issue and I think it can be closed?
