### ISSUE TITLE
Eliminate MD rule suppression for first line in file being a top level header

### ISSUE THREAD

**Issue by shredtechular** [m-lab/m-lab.github.io#198]
The linter rule is 'MD041' and pretty much every page is failing this rule.

I think this is because the yml frontmatter is being considered the first line, so not sure there will be much we can do about this issue other than modifying the mdl linter to exclude yml frontmatter.  However, even if we did that, then we would still have some pages that would fail with our current ToC implementation which needs to be at the top of the file and not be a top level header.

**Comment by critzo** [comment]
This rule is being excluded, so is a non-issue.
