### ISSUE TITLE
Details tab of NDT results has improperly formatted fractions/percentages

### ISSUE THREAD

**Issue by nkinkade** [m-lab/m-lab.github.io#209]
The "Details" tab of NDT results has two lines like the following, for example:

```
0.9808 % of the time was not spent in a receiver limited or sender limited state.
0.0000 % of the time the connection is limited by the client machine's receive buffer.
```

These numbers should probably be multiplied by 100 to make the % more sensible.

**Comment by critzo** [comment]
@nkinkade This is actually an issue that should be raised in the NDT repo if it hasn't already. 
I've created an issue there (https://github.com/m-lab/ndt/issues/72) and will close this one.
