### ISSUE TITLE
Proper name for NDT

### ISSUE THREAD

**Issue by collina** [m-lab/m-lab.github.io#214]
Across the site, the Network Diagnostic Tool is written as Network Diagnostic Test. We should update this to be correct.

**Comment by stephen-soltesz** [comment]
I just noticed this also. So, +1

**Comment by critzo** [comment]
Replacing instances of "Network Diagnostic s/Test/Tool/" from these pages:
* _pages/03-tests.md L14
* _pages/07-publications.md L63
* _pages/faq.md L35
* _pages/home.md L27, 30
* _pages/tools/ndt.md L4, 8, 10
* _pages/who.md L76
