### ISSUE TITLE
Startcom (M-Lab Sites's CA) is deprecated

### ISSUE THREAD

**Issue by collina** [m-lab/m-lab.github.io#219]
Related: https://blog.gerv.net/2016/10/wosign-and-startcom/

Nodes use Thawte, which should be okay. But perhaps we should plan to move to Let's Encrypt?

**Comment by nkinkade** [comment]
It doesn't appear that CloudFront supports Let's Encrypt. But Amazon has it's own certificate management tool (ACM), and I've generated a wildcard certificate for `*.measurementlab.net` and applied it to both www.measurementlab.net and speed.measurementlab.net. The certs are signed by Amazon's own CA, which is apparently supported by all major browsers.

**Comment by collina** [comment]
@nkinkade: That's fine, but to be clear, CloudFront definitely supports Let's Encrypt.
