### ISSUE TITLE
add blacklist_flags field to schema description and update schema page

### ISSUE THREAD

**Issue by critzo** [m-lab/m-lab.github.io#223]
While the blacklist_flags field was added to our tables, when showing table descriptions via the command line tools (ie: bq show <table name>) the field is not displayed along with the other fields in the schema. 

Investigate why, fix and update documentation on the schema page.

**Comment by georgiamoon** [comment]
@critzo didn't you do this?

**Comment by critzo** [comment]
@georgiamoon Yes. I'm reviewing all the old site issues. This one is resolved. Closing.
