### ISSUE TITLE
Integration Tracking

### ISSUE THREAD

**Issue by collina** [m-lab/m-lab.github.io#226]
https://broadband.cgit.vt.edu/BroadBandSurvey/survey/speedtest/

**Comment by critzo** [comment]
http://vis-mlab.internet-measurement.com/

**Comment by critzo** [comment]
the Berlin-based technology foundation, Technologiestiftung Berlin, went live today with their NDT integration. You can find the test here:
http://www.breitband-berlin.de/#speedtest

**Comment by critzo** [comment]
https://www.highspeedinternet.com/ Uses the NDT iframe embed code.

**Comment by georgiamoon** [comment]
move to project-tracker repo

**Comment by critzo** [comment]
https://www.westlondon.com/techwestlondon/partners/internet-connection-speed/

**Comment by critzo** [comment]
I moved these links to the relevant project tracker issue: https://github.com/m-lab/project-tracker/issues/29
