### ISSUE TITLE
Check all DNS records and redirect stale domains to correct locations

### ISSUE THREAD

**Issue by critzo** [m-lab/m-lab.github.io#230]
- measurement-lab.org goes to an old planet lab page that does not seem to include any pointers to our current pages.

Audit all DNS records and redirect them where needed:
- measurement-lab.org
- .org, .com, .net

**Comment by stephen-soltesz** [comment]
We should move:
https://github.com/m-lab/operator/blob/master/plsync/mlabzone.header.in

To https://github.com/m-lab/dns-zones

mlabconfig.py has the logic to use it, but the dependencies should be in dns-zones.

**Comment by stephen-soltesz** [comment]
There is still a reference to chambana.net in the measurementlab.net zone.

https://github.com/m-lab/dns-zones/blob/master/measurementlab.net#L14

$ host mail0.frost.chambana.net
mail0.frost.chambana.net has address 165.117.251.93

**Comment by critzo** [comment]
I've replicated the comments here in https://github.com/m-lab/dns-zones/issues/4
