### ISSUE TITLE
Add MeasurementKit to the m-lab website

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/m-lab.github.io#240]
Add MeasurementKit to the M-Lab website and perhaps a page about client integrations and recommendations

**Comment by critzo** [comment]
We currently have a couple places where this might live:
* Data / Tools - https://www.measurementlab.net/data/tools/
* Contribute - https://www.measurementlab.net/contribute/#use-an-m-lab-test-in-your-website-or-application
* FAQ entry - https://www.measurementlab.net/faq/#how-can-i-add-an-m-lab-test-to-my-website-app-or-other-software

Perhaps it's time to add a new top level site section, "Developers" ? It could initially include content from:
* https://www.measurementlab.net/contribute/#develop-a-test
* https://www.measurementlab.net/contribute/#use-an-m-lab-test-in-your-website-or-application

And of course include reference to measurement kit. This section would also be a placeholder for a future developer reference or guide. Thoughts @georgiamoon ?

**Comment by critzo** [comment]
Following up on this issue, MK was added to the [developer guide](https://www.measurementlab.net/develop) and I've added a short reference to it on the [Data/Tools page](https://www.measurementlab.net/data/tools/). The Contribute page and FAQ both link to the Developer Guide, so I think we're good. Adding a commit and PR shortly.
