### ISSUE TITLE
Updates to Observatory pages re: deprecation

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/m-lab.github.io#252]
Let's:
- [ ] add a note to go to the compare section of the new Viz (http://www.measurementlab.net/observatory/)
- [ ] find a new home for some of the explanatory content and glossary content, because it's still good. (http://www.measurementlab.net/observatory/#tab=help&)

**Comment by critzo** [comment]
For deprecation and redirect notice, I suggest that we can update the text in the modal box that appears on first loading the Observatory page:

![image](https://cloud.githubusercontent.com/assets/4633345/25675905/1ff86e20-300e-11e7-8ea0-a38c463da3b4.png)

**Comment by georgiamoon** [comment]
I think that works. I would also put it on the page either right above the
page title or right above the main content, as someone might click through
automatically and not read the modal dialog.

**Comment by critzo** [comment]
I agree. Putting the same message both places- on the page and in the modal. I'll mock this up in a branch as a next step.

**Comment by critzo** [comment]
@georgiamoon I've started a mockup of this content change on my fork. Should be previewable for your review and comment in a few minutes:
https://critzo.github.io/m-lab.github.io/

Currently there is a new menu tab with two sub-pages containing content from the observatory. Mockup of the text change to the Observatory has not yet been done.

**Comment by critzo** [comment]
@georgiamoon My fork has been updated to include a [message on the Observatory page](https://github.com/critzo/m-lab.github.io/commit/c5d124df6f5997725ddcd8571bd0eb1e2c49e8b0). A commit will be needed in the mlab_observatory repo to add the message to the modal dialog, but I've mocked it up in my locally running site build. See image below. Does this message look ok?

![image](https://cloud.githubusercontent.com/assets/4633345/26131008/73cab4ca-3a65-11e7-9624-c4d8747fc7f5.png)

**Comment by georgiamoon** [comment]
I think that looks good. I might use the language "retired" and add a date as to when it was last updated?

@collina any thoughts?

**Comment by georgiamoon** [comment]
Also -- I think we'd want to remove the "Don't show this message again" prompt, because we want to show that message everytime now. Does that make sense to you both?

**Comment by critzo** [comment]
Makes sense to me. Additional question- Do we want to show the observatory
charts on the page behind the modal at all? Just the message about it being
replaced and a link to the viz site? Take it a step further, we could just
change the page type and not display the modal at all.

**Comment by georgiamoon** [comment]
I think we do want to show the charts because we want to observatory to still be useable, since it's referenced in publications and comments.

The other option would be to remove the modal, and make that note at the top of the content page. I'm a little pro the modal since it will actually force the user attention to the message, where on the site it would be overlooked.

**Comment by critzo** [comment]
@georgiamoon @collina 
I've updated my master branch with the suggested text revisions (Retired instead of Replaced). I've also tied the mlab_observatory submodule in my fork to a feature branch containing the modal dialog updates. This commit adds the modal's buttons back in as well, with updated text and link.

Preview: https://critzo.github.io/m-lab.github.io/

PTAL?

**Comment by georgiamoon** [comment]
I think this looks like a good solution -- @collina?

**Comment by critzo** [comment]
@collina If you have any blocking concerns on this approach, please let us know. 

I'm also looking now at adding a redirect for the Observatory/Interconnection report data/graphs that are referenced in the report, per the recent support request.

**Comment by georgiamoon** [comment]
Thanks @critzo!

**Comment by collina** [comment]
Fine by me. Thanks Chris.

**Comment by critzo** [comment]
Awesome. Thanks!
