### ISSUE TITLE
Eliminate htmlproofer suppressions

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#27]
htmlproofer is failing on some pages. We should determine the cause of the failures and fix the root causes. We generally should not be disabling htmlproofer.

One example is in `.travis.yml`:
`- bundle exec htmlproof ./_site --only-4xx --check-html --file-ignore "/mlab_observatory/" --href-ignore "http://projectbismark.net/signup.html"`

We should remove the ignores. Are there others?

**Comment by shredtechular** [comment]
Here is one more example of a broken link that we may need to add an ignore on the htmlproofer to temporarily solve.

On this page (http://www.measurementlab.net/who/), there is a link to http://www.measurementlab.net/getinvolved, however, this page does not exist on the current site.  Any thoughts on where that is supposed to go?  Maybe to /contribute/ perhaps?

On that same page, there are also several links on that page linking to the same page itself (/who/).  This doesn't break html proofer per say, but felt like I'd mention it here to be sure that's what is desired.

**Comment by critzo** [comment]
Andrew,
The link to "get involved" should go to the contribute page, as you
suggested. The links to /who/ on this page can be removed.

Thanks,
Chris

**Comment by shredtechular** [comment]
Thanks for the clarifications @critzo .  I made these updates in the https://github.com/m-lab/m-lab.github.io/pull/41 pull request.

**Comment by mtlynch** [comment]
Adding to the list of things we want to grep for and remove at some point:

* `href-ignore`
* `data-proofer-ignore`
