### ISSUE TITLE
remove old GSOC page?

### ISSUE THREAD

**Issue by critzo** [m-lab/m-lab.github.io#283]
So this page exists:
https://www.measurementlab.net/page/gsoc_2014/

Do we want to removed it? @georgiamoon

**Comment by critzo** [comment]
This page is only referenced by the [blog post](https://www.measurementlab.net/blog/gsoc_2014/) that accompanied it. I would suggest that we simply move the content from this page to the end of the blog post and remove the page itself. Thoughts @georgiamoon ?

**Comment by georgiamoon** [comment]
Sounds good to me.
