### ISSUE TITLE
Update Privacy Policy and AUP (#245)

### ISSUE THREAD

**Issue by collina** [m-lab/m-lab.github.io#286]
Per the staff call, and our lengthy consultation process connected to ticket #245. Can you post these two statements about Privacy and the AUP, @critzo? The original formatting has anchor tags which are useful and reused here, can we keep them? Let's also have the table of terms be a third section in the page with its own anchor, since it's referred to in AUP, and I think will arise elsewhere as a durable resource?

Relatedly, can we create privacy@ -- aliasing to support@ is fine.

Privacy Policy: https://docs.google.com/document/d/1c-lc3_9Ft-FHhhnjNy15cV4pGQt_vqGV1YLucB0HD1M/edit
Acceptable Use Policy: https://docs.google.com/document/d/1lnbRaolTf9-OukD60GHcgKp6pHSoVQDDbaucT9OBgkQ/edit

Thank you!

**Comment by critzo** [comment]
@collina Thanks for shepherding these docs. I'll get them added to a pull request.
