### ISSUE TITLE
Privacy Policy formatting issues

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/m-lab.github.io#290]
https://www.measurementlab.net/privacy/

There are some formatting issues that seem to have happened with the update.

**Comment by critzo** [comment]
@georgiamoon What are the issues? We can discuss irl if you would prefer.

**Comment by critzo** [comment]
I have some changes to address this in a branch on my fork.

**Comment by critzo** [comment]
Here's a preview of the changes that will appear in an upcoming PR. 
![image](https://user-images.githubusercontent.com/4633345/29043192-14ce504e-7b88-11e7-8cf1-7d5c73954ef8.png)
![image](https://user-images.githubusercontent.com/4633345/29043238-400a8282-7b88-11e7-8027-afec5020c039.png)
![image](https://user-images.githubusercontent.com/4633345/29043244-4d02d34a-7b88-11e7-87f0-9e90963b7e07.png)

**Comment by mlab-code-reviews** [comment]
I think that looks better -- thanks!
