### ISSUE TITLE
Permalinks on category pages all go to the first blog post in the category

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/m-lab.github.io#334]
Category Page: https://www.measurementlab.net/blog/category/interconnection/

All permalinks go to some version of the first post in the category: https://www.measurementlab.net/blog/interconnection_update/

**Comment by critzo** [comment]
This will be a change to [blog-archive.html](https://github.com/m-lab/m-lab.github.io/blob/master/_layouts/blog-archive.html)

**Comment by critzo** [comment]
After some further testing, the PR for this will touch a larger number of files. The permalink anchor tags are being added globally in [NavigationEnhancer.js](https://github.com/m-lab/m-lab.github.io/blob/master/js/src/controllers/enhancers/NavigationEnhancer.js). 
* _NavigationEnhancer.js_ will be modified to exclude the the blog category and date archive pages, essentially making it add anchor tags on static pages (not looped pages with multiple posts)
* To replace that functionality on the category and archive pages, we will make individual templates (blog-category-archive.html and blog-date-archive.html), replacing the single template that's currently doing both, ([blog-archive.html](https://github.com/m-lab/m-lab.github.io/blob/master/_layouts/blog-archive.html) )
* We'll also remove the page title and "post-meta.html" include within each blog post, adding this content to the "blog.html" template
* And finally, we will add permalinks back onto the blog index page, using similar strategy. 

PR for this should come on Thu 4/5 @georgiamoon

**Comment by critzo** [comment]
Addressed by #360.
