### ISSUE TITLE
Exclude extensions for publications

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#34]
For publication links like:

http://m-lab.github.io/publications/isp-interconnection-impact.pdf

Can we remove the extension so it's just:

http://m-lab.github.io/publications/isp-interconnection-impact

**Comment by shredtechular** [comment]
As the pdf file is an asset within the codebase, we can't simply add metadata to it to apply permalinks or have jekyll apply that type of extensionless URL.

Is the concern links from external sources may break to any pdfs that are apart of the codebase (i.e. - not the ones hosted on google...) once the site is migrated over to GitHub pages?  Or is it more of an aesthetic appearance of an extensionless URL that is desired?

I can think of 2 possible solutions that we could consider, depending on the thought behind preferring extenionless pdf URLs:

1. Using a js redirect?  To my knowledge, GitHub pages doesn't support mod_rewrite or .htaccess types of Apache server rules.  However, we could consider some kind of redirect -- js (preferred) or meta redirect.  For example, if the user clicked on a link or typed in http://m-lab.github.io/publications/isp-interconnection-impact we could have a redirect to the extension URL of http://m-lab.github.io/publications/isp-interconnection-impact.pdf.  I don't know if this would help solve the issue from an aesthetic perspective though?

2. We may also be able to emded the pdf within a plain html page or use some type of 3rd party js pdf viewer.  I do have some concerns when it comes to browser compatibility for this, but I imagine we could get this to work pretty well on most main desktop browsers.  Here is one pdf viewer from mozilla that some folks have recommended, though some folks were concerned with performance of it: https://github.com/mozilla/pdf.js.  Or we could use an iframe/embed/object tag to embed the pdf, however, I don't think this would look too appealing?

A mod_rewrite would be perfect here, so I'll keep digging to see if there is some way to do that with GitHub pages, but so far no luck seeing this as possible...

**Comment by shredtechular** [comment]
UPDATE: I was able to get an example of an embed working if you'd like to take a look at it here: https://andrew-m-lab.github.io/publications/2013-measuring-broadband-america/

What do you think about this?  If you like this, I can implement this feature with the rest of the PDF/Publications and update the links throughout the site.

**Comment by critzo** [comment]
@mtlynch can you say more why having extension-less URLs to PDFs is needed?

@shredtechular I think it would be useful to be able to provide aliases to
existing content that may have had a different URL in the past. For
example, we recently found a link in a PDF document that pointed to a pdf
under the old old drupal site structure. It would be convenient to alias
that old URL to the updated link.

**Comment by mtlynch** [comment]
@critzo Just seems a little cleaner to me. It seems like there's been a move away from extensions in URLs for most sites. Plus it gives us a little more flexibility in the future because it will be the default link we use to share the papers, but if we decide in the future we actually want it to go to an HTML abstract of the paper (then let users download the PDF from that page), excluding ".pdf" from the URL makes it easier for us to do that.

@shredtechular - That looks good to me. @critzo does that work for you?

**Comment by critzo** [comment]
@mtlynch I think I would rather just link to the PDF files with an
extension.

@georgiamoon what do you think?

**Comment by georgiamoon** [comment]
I would expect a link without an extension to be the blog post / overview
and the link with the extension to be the PDF itself.

I think we're all getting at the same thing though, but maybe just
referring to different examples?

**Comment by mtlynch** [comment]
Sounds like the existing scheme is what we want. Closing this.
