### ISSUE TITLE
Publish PT issue & remediation blog post

### ISSUE THREAD

**Issue by critzo** [m-lab/m-lab.github.io#348]

**Comment by georgiamoon** [comment]
@pboothe @yachang @gfr10598 putting this on your radar to complete before the 10 year event. Since this never was completed in the spring

cc @kokosta

**Comment by critzo** [comment]
@pboothe @yachang @kokosta - This was one of the blog posts we discussed last week, but did not touch on in the sprint issue triage this morning. Added the appropriate tags.

**Comment by kokosta** [comment]
Thanks @critzo !
