### ISSUE TITLE
raw storage location needs to be updated

### ISSUE THREAD

**Issue by critzo** [m-lab/m-lab.github.io#369]
This is the current bucket being published to:
https://console.cloud.google.com/storage/browser/archive-mlab-oti

We need to create a new bucket in the project `measurement-lab` named `archive-measurement-lab` where all data for all tests will be published

**Comment by critzo** [comment]
Discussed on the staff call. We will:
[ ] create a new bucket in the measurement-lab `archive-measurement-lab`
[ ] change the location of our ETL pipeline to publish to the new bucket
[ ] move the old data to the new bucket
[ ] update documentation on website

**Comment by georgiamoon** [comment]
@pboothe please let us know when this is implemented, so we can update the docs. cc @gfr10598

**Comment by critzo** [comment]
Added P0 and review/triage tags.

**Comment by pboothe** [comment]
First copy job is in progress.

**Comment by pboothe** [comment]
We are now pruning the data to ensure that we will create a good, coherent, unified archive with minimal redundancy and no data loss.  

Each step that Soltesz and I are doing is being recorded at: https://github.com/m-lab/etl-gardener/issues/44

**Comment by pboothe** [comment]
Last step is setting up a regular transfer from archive-mlab-oti to archive-measurement-lab.  Will be done today.

**Comment by pboothe** [comment]
https://console.cloud.google.com/storage/transfer/details/17702947467706106145?project=measurement-lab

**Comment by pboothe** [comment]
M-Lab public archives are now unified at the `archive-measurement-lab` bucket.

Every project still uses its own buckets for every stage of the pipeline, but the measurement-lab project copies all the data from `archive-mlab-oti` every day.

**Comment by pboothe** [comment]
@critzo Done.

**Comment by critzo** [comment]
reopening this issue since it relates to updating the documentation for this, which as not yet been done @pboothe

**Comment by critzo** [comment]
resolved in https://github.com/m-lab/m-lab.github.io/pull/404

**Comment by critzo** [comment]
@kokosta Please leave issues in this repository open until the website has been updated. If this type of issue needs to be opened in a different repo for sprint/task tracking on the dev side, please let me know where to do so.
