### ISSUE TITLE
Restructure content on the front page

### ISSUE THREAD

**Issue by critzo** [m-lab/m-lab.github.io#379]
Based on recent conversations, we desire some content restructuring on the front page of the site. The following changes have been discussed, placed here for comment and further discussion.

* remove rotating slide show, replace with some other more interesting content
* remove "highlighted visualization"
* move up/prioritize recent blog posts
* add other interesting content related to the platform

**Comment by georgiamoon** [comment]
Related to #277

**Comment by georgiamoon** [comment]
Related to #381

**Comment by critzo** [comment]
@georgiamoon I've taken a first pass at restructuring the front page and related items we discussed. Could you take a look and I'll make any changes before submitting a PR? https://critzo.github.io/m-lab.github.io/
