### ISSUE TITLE
SideStream updates

### ISSUE THREAD

**Issue by critzo** [m-lab/m-lab.github.io#425]

**Comment by stephen-soltesz** [comment]
What does "table freeze" refer too? This sounds like an idea that pre-dates the discovery that we do not need to embargo the sidestream data any more. Now there is no freeze. Everything should be published as part of the gardener reprocessing of sidestream.

**Comment by stephen-soltesz** [comment]
I think this can be combine with the BQ dataset renaming.

**Comment by critzo** [comment]
Sounds good. Thanks @stephen-soltesz
