### ISSUE TITLE
Change in PDF URLs requires aliases for old URLs

### ISSUE THREAD

**Issue by critzo** [m-lab/m-lab.github.io#65]
When we moved content into the new site, we moved PDFs to new URLs. We need to create an alias to support the old URLs so they automatically redirect to the new ones. 

For example this PDF:
http://www.measurementlab.net/static/observatory/M-Lab_Interconnection_Study_US.pdf

is now at this URL:
http://www.measurementlab.net/publications/isp-interconnection-impact.pdf

@mtlynch @shredtechular Any thoughts on how to accomplish this?

**Comment by shredtechular** [comment]
Hmm, 3 possible solutions that I can think of:

1. There are ways to do redirects with Jekyll, for example, [here](https://help.github.com/articles/redirects-on-github-pages/) and [here](https://github.com/tsmango/jekyll_alias_generator), and I like keeping a list of redirects under some version control and with the codebase so all environments are reacting the same way.  However, from an SEO perspective, these plugins are not advisable.  I also don't know if we would be able to redirect pdfs with these.  I think we would have to redirect the original pdf to perhaps the /publications/ page and even then I'm not positive this would work in all environments.  We would definitely need to test this out on s3/github pages/locally to see how it would handle this.

2. As this is hosted on s3, [would creating 301 redirects in AWS] (http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html)be an option?  It isn't exactly the same as an alias, however, I think many folks believe that a 301 is better from a usability perspective so users don't get confused about same content on multiple urls?  Downside is other non production environments wouldn't have any visibility into these configurations, but if they are limited to pdf files on outdated urls, maybe not much of a concern?

3. Also, it could be conceivable to move to an EC2 instance and configure them with an .htaccess file that could be under source control.  But I assume that is not a desired path to go...

**Comment by critzo** [comment]
I think 301 redirects are probably the best option. There aren't that many of them, but the example one I provided has been pretty highly publicized. @nkinkade can you add a 301 redirect for the Interconnection study PDF in AWS?

**Comment by critzo** [comment]
Digging through old tickets. I just read the Amazon S3 doc on adding 301 redirects: https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

I'll investigate further but it seems you have to add the redirect on an existing file? Which in this case likely does not exist in the current site. @georgiamoon maybe you have experience doing this in S3?

**Comment by critzo** [comment]
We can do redirects in AWS S3, but it's a little more involved than just adding lines to an .htaccess file.
Here's how we do it in this case.
- create a blank text file with the same filename as the old content you wish to redirect. for example in this issue, we want to redirect http://www.measurementlab.net/static/observatory/M-Lab_Interconnection_Study_US.pdf so I'll create a file named _M-Lab_Interconnection_Study_US.pdf_ and save it in `/static/observatory`
- after deploying this new file to AWS, login to the [S3 Management Console](https://console.aws.amazon.com/s3/buckets/www-measurementlab-net/static/observatory/?region=us-east-1&tab=overview), click on [the file](https://console.aws.amazon.com/s3/object/www-measurementlab-net/static/observatory/M-Lab_Interconnection_Study_US.pdf?region=us-east-1&tab=overview) you just uploaded and then click on Properties > Metadata
- add a metadata item and using the [instructions from AWS](https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html), add the redirect location as a metadata item.

**Comment by critzo** [comment]
Add this documentation on how to do redirects into the Readme.
