### ISSUE TITLE
Add Travis check for trailing whitespace

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#75]
We should add a Travis check to make sure that files in this repo do not have trailing whitespace (at the very least .md and .yml files).

This can either a simple grep for "\s+$" or can be a more thorough check using a Markdown linter (bonus points if we can smoothly integrate a markdown linter into Travis/git hooks, especially one that reflows lines to break at 80 columns)

**Comment by mtlynch** [comment]
@shredtechular can you take this on after tackling the style issues?

**Comment by shredtechular** [comment]
@mtlynch Absolutely, I can see what I can figure out that may help with that respect after the styling fixes are complete.
