### ISSUE TITLE
Eliminate MD rule suppression for trailing punctuation in header

### ISSUE THREAD

**Issue by shredtechular** [m-lab/m-lab.github.io#88]
The linter rule is 'MD026' and the failing pages currently are:
- /about page - has a couple headers with "?" at the end.  I think this is okay.
- /page/gsoc_2014/ - has 1 header with an "!" at the end.  I think this is okay?
- /tools/pathload2/ - has 1 header with an "." at the end.

We can modify this rule so that some punctuation is allowed and others are not.  By default, the linter doesn't accept the following punctuation at the end of headers: ' . , ; : ! ? '.

I don't think the h2 is very semantically correct on /tools/pathload2/, so probably just need a decision on if that should really be an h2 or if so, then can we remove the "." at the end?

@critzo @georgiamoon @mtlynch can you provide the business rule for what punctuation you would like to allow at the end of header levels?  It seems like I could make a case for allowing ' : ! ? ' but maybe not ' . , ; '.

**Comment by mtlynch** [comment]
Don't have a strong opinion. I defer to @critzo and @georgiamoon

**Comment by critzo** [comment]
This linter rule is being excluded. Closing.
