### ISSUE TITLE
Create embeddable iframe for NDT HTML5 test

### ISSUE THREAD

**Issue by mtlynch** [m-lab/m-lab.github.io#92]
I'd like us to make it as easy as possible for third parties to drop in the HTML5 NDT test onto their own sites in the form of an iframe.

This involves fixing the following sub-issues:
* Make the widget self-contained so that it has M-Lab's logo and a link back to M-Lab's site and brief text explaining that it's a bandwidth test. It shouldn't require surrounding context of the page to explain what the widget is.
* Add a button to the widget that generates the HTML required for embedding
* The client currently generates a JS warning: `Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.` It's likely that mlab-ns isn't going to delay the page load much, but it'd be nice to avoid this. I think we can build more intelligence into the widget so that it the widget handles waiting for the mlab-ns response.

If any of these changes require patches to ndt-project/ndt, we can submit a PR to them.

**Comment by shredtechular** [comment]
I'm not able to close issues, so leaving a comment that I think PR #111 addressed this issue and I think it can be closed?
