### ISSUE TITLE
Create custom error page

### ISSUE THREAD

**Issue by nkinkade** [m-lab/m-lab.github.io#96]
Just a note that we should probably create a custom error page.  Currently 404s (and other errors) look like this:

http://www.measurementlab.net/lol

A custom error document can be set in the CloudFront configuration.

**Comment by shredtechular** [comment]
We have a 404 page created here: [https://www.measurementlab.net/404.html](https://www.measurementlab.net/404.html), although it does look like there is some styling off on it that could use some fixing.

In order for the error page to work for github pages it needs to live at this URL, but does that provide enough information to create the CloudFront configuration?
