### ISSUE TITLE
Link to NPAD test on NPAD page broken

### ISSUE THREAD

**Issue by nkinkade** [m-lab/m-lab.github.io#99]
The "Run NPAD" link on our NPAD page is broken. This was a known issue, but for some reason [the ticket was closed](https://github.com/m-lab/mlab-ns/issues/38) without a good explanation.  Any update on this?

**Comment by mtlynch** [comment]
That ticket is still open:

![image](https://cloud.githubusercontent.com/assets/7783288/13820280/09595bec-eb73-11e5-90b3-98eeb1720b74.png)

It's confusing Github UI at the bottom though. What was actually closed was a bug in the m-lab.github.io repo: https://github.com/m-lab/m-lab.github.io/issues/84
